#!/bin/bash
source functions.sh

VARS='KF_SERVER_NAME KF_SERVER_SHORT_NAME KF_SERVER_PASSWORD KF_ADMIN_NAME KF_ADMIN_EMAIL KF_ADMIN_PASSWORD KF_GAME_LENGTH KF_GAME_DIFFICULTY KF_PORT_GAME KF_PORT_GAMESPY_QUERY KF_PORT_WEBADMIN';

if [ -z "${KF_SERVER_PASSWORD}" ]; then
	KF_SERVER_PASSWORD='';
fi;

if [ -z "${KF_GAME_LENGTH}" ]; then
	KF_GAME_LENGTH=2;
fi;

if [ -z "${KF_GAME_DIFFICULTY}" ]; then
	KF_GAME_DIFFICULTY=7.000000;
fi;

if [ -z "${KF_PORT_GAME}" ]; then
	KF_PORT_GAME=7707;
fi;

if [ -z "${KF_PORT_GAMESPY_QUERY}" ]; then
	KF_PORT_GAMESPY_QUERY=7717;
fi;

if [ -z "${KF_PORT_WEBADMIN}" ]; then
	KF_PORT_WEBADMIN=8075;
fi;

if [ -z "${KF_MAP}" ]; then
	KF_MAP=KF-BioticsLab;
fi;

overwrite_default_file /data/System/Default.ini /app/killing-floor/System/Default.ini.example /app/killing-floor/System/Default.ini $VARS;
link_data /data /app/killing-floor;
copy_in_vars /data/System/Default.ini /app/killing-floor/System/Default.ini $VARS;

cd killing-floor/System;
exec ./ucc-bin server "${KF_MAP}.rom?game=KFmod.KFGameType?VACSecured=true" -nohomedir ini=Default.ini

