#!/bin/bash
source functions.sh

VARS='KF_SERVER_NAME KF_SERVER_SHORT_NAME KF_SERVER_PASSWORD KF_ADMIN_NAME KF_ADMIN_EMAIL KF_ADMIN_PASSWORD KF_PORT_GAME KF_PORT_GAMESPY_QUERY KF_PORT_WEBADMIN';

if [ -z "${PORT_GAME}" ]; then
	PORT_GAME=7707;
fi;

if [ -z "${PORT_GAMESPY_QUERY}" ]; then
	PORT_GAMESPY_QUERY=7717;
fi;

if [ -z "${PORT_WEBADMIN}" ]; then
	PORT_WEBADMIN=8075;
fi;

link_data /data /app;
overwrite_default_file /app/System/Default.ini /app/System/Default.ini.example $VARS;
copy_in_vars /app/System/Default.ini $VARS;

cd System;
exec ./ucc-bin server KF-BioticsLab.rom?game=KFmod.KFGameType?VACSecured=true -nohomedir ini=Default.ini

